### PR TITLE
Update Greg Package version

### PR DESCRIPTION
**Pull request by ZiyunShang**
### Purpose

Update Greg Package version to keep consistent with DynamoCore.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.

### Reviewers

@AndyDu1985 @QilongTang @mjkkirschner

### CODE REVIEW

**Comment by ZiyunShang** [comment]
Hi @QilongTang @mjkkirschner , is there any other package version should be upgraded when integrate DynamoCore final version(2.2.0.4667) into Revit?

**Comment by QilongTang** [comment]
@ZiyunShang @mjkkirschner I think this is it.

**Comment by mjkkirschner** [comment]
You may want to try updating GregRevitAuth as well.

**Comment by ZiyunShang** [comment]
@mjkkirschner  GregRevitAuth does not have a new package on Nuget.org yet (https://www.nuget.org/packages/GregRevitAuth/)

**Comment by mjkkirschner** [comment]
@ZiyunShang thanks - I will publish another tomorrow so that the latest PR on that repo is available.

My worry is that Greg now targets .net 4.7 so GregRevitAuth should probably be updated to target .net 4.7 as well - for max compatibility. (this was done in the last PR there)

**Comment by ZiyunShang** [comment]
@mjkkirschner OK, thank you, Michael! 
BTW, do other packages like DynamoVisualProgramming.Core need to be updated to 4667? They are still 4565 on nuget.org.(https://www.nuget.org/packages/DynamoVisualProgramming.Core/)

**Comment by QilongTang** [comment]
@ZiyunShang @mjkkirschner Nope, and this has been a constant question. The public nuget only need to be updated when there are public API changes. Version does not necessarily need to align with DynamoCoreRuntime

**Comment by ZiyunShang** [comment]
Hi @mjkkirschner @QilongTang , is there anything else that needs improvement?

**Pull request merged**
