### PR TITLE
add the option to shutdown existing RevitDynamoModel

### PR DESCRIPTION
**Pull request by BogdanZavu**
### Purpose

In order to be able to run a graph in a different Revit document than the one we started with, we need to shutdown the existing RevitDynamoModel.

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [X] Snapshot of UI changes, if any.

### Reviewers
@mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@BogdanZavu - this looks good to me, - is there any reason to keep this code out of 2016/2017 as well or can you make cherry pick branches for those revit branches?

I cannot recall if all previous PRs you made went to those versions as well or only 2018?

**Comment by BogdanZavu** [comment]
@mjkkirschner All the previous PR went to both 2017 and 2018. This one also needs to be in 2017.
I'll create another pull request for that.

**Comment by mjkkirschner** [comment]
@BogdanZavu - just an update - this is ready to go, but we're merging a bunch of revit functionality with lots of conflicts and shared resources so I'm going to hold off on merging this for about another week.

**Comment by BogdanZavu** [comment]
@mjkkirschner Ok. I also created another PR for Revit2017 branch.

**Pull request merged**
