### PR TITLE
rename filter category

### PR DESCRIPTION
**Pull request by moethu**
### Purpose

Fixed Revit Filter Category

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@mjkkirschner thanks, guess this makes sense but it didn't work for me.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@moethu I will look into this - we should get it working on on your machine before merge.

**Comment by mjkkirschner** [comment]
this works fine on my local build see:

screen shot 2016-08-23 at 9 29 12 pm
screen shot 2016-08-23 at 9 29 18 pm

The revit nodes category still exists because the enum is still exposed so that will go away when we get rid of that enum later.

**Comment by mjkkirschner** [comment]
if you the same as me, please generate the 2017, 2018 branches and I'll merge.

**Comment by mjkkirschner** [comment]
@moethu ping on 2017 and 2018 cross merges.

**Comment by moethu** [comment]
@mjkkirschner  done

**Pull request merged**
