### PR TITLE
Upgrade DynamoCore Lib to involve new version of Sample rvt file.

### PR DESCRIPTION
**Pull request by wangyangshi**
upgrade sample rvt file

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by wangyangshi** [comment]
@QilongTang Hi Aaron 
I change these version to `2.18.0-beta3734`, but in DynamoRevitUtil, still keep dynamo core version as `2.17.0.3472`
https://git.autodesk.com/Dynamo/DynamoRevitUtils/blob/5bc7844345781fa3a12c1ead21815f57f61c926d/BuildSolutions.bat#L16

is it right, I referred to this: https://github.com/DynamoDS/DynamoRevit/pull/2787/files

**Comment by QilongTang** [comment]
hmm.. I feel you only need to change the version of the sample nuget, these versions do not need to always align to the same minor number. What do you think @mjkkirschner

**Comment by wangyangshi** [comment]
@QilongTang  thank you I will change only the sample version

**Comment by wangyangshi** [comment]
https://git.autodesk.com/Dynamo/DynamoRevitUtils/pull/86
at DynamoRevitUtils, in the build script,  `DynamoSamples` use the version of `DynamoVisualProgramming.Core`,
so I change it to `2.18.0-beta3734` instead of `DCoreVersion`

**Review by ShengxiZhang — APPROVED** [review]

**Review by QilongTang — APPROVED** [review]

**Review by mjkkirschner — APPROVED** [review]

**Pull request merged**
