### PR TITLE
Updating Readme so it shows the correct location of the addin file

### PR DESCRIPTION
**Pull request by Racel**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs that do not have template completely filled out and all declarations satisfied will not be reviewed by the Dynamo team.
6. PRs made to the `Dynamo` repo will need to be cherry-picked into all the Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

The purpose of this PR is to update the Readme with instructions on how to build D4R.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@mjkkirschner @QilongTang

### FYIs

@sharadkjaiswal

### CODE REVIEW

**Comment by Racel** [comment]
@mjkkirschner @QilongTang - I meant to do this a while ago, but just found the note I made to myself. When trying to test Dynamo4Revit, I realized that the path to the addin was wrong in the readme (at least for Revit 2017 on my machine).

Please let me know if this is the case for the other Revit versions we support (2016,2018). I will cherry-pick as needed. Or, if my system is just different from other setups. If that is the case, please just close this PR.

**Comment by Racel** [comment]
Revit is looking for the addin in multiple places. We should update this PR to have all the places.

@sm6srw - can you provide all the locations and for which users?

**Comment by Racel** [comment]
@QilongTang @mjkkirschner - Revit told me where they look for addins: https://gist.github.com/teocomi/5986db4eba261ec4baeb7325329aa226

Added 3 locations. Left the location where they look for addins that are packaged for the Autodesk Exchange store. Let me know if I should add it and if this looks good to merge.

**Comment by mjkkirschner** [comment]
@Racel this is almost correct now, I think we need to mention the dynamo config file that Sharad told us about, @QilongTang maybe we can fill that in later though after this is merged?

**Comment by Racel** [comment]
@mjkkirschner - Which config file? I can add it, if necessary.

**Comment by QilongTang** [comment]
@Racel It is when you build D4R, it generates a Dynamo.Config at DynamoRevit\bin\AnyCPU\Debug. This file can be used in several cases to specify the path to Dynamo Core you want your D4R to work with.
1. In the case that you have an installed version of Dynamo Core and you have a built version of Dynamo Core
2. When using RTF

There might be other cases that I am not aware of

**Comment by Racel** [comment]
@QilongTang - Can you tell me the details on how to specify the path since it appears to not be there by default? I can add it to this PR.

**Comment by Racel** [comment]
@QilongTang - Ping. Can you take a look at this and let me know specifically what needs to be added? If not, let us go ahead and merge this and file a separate PR to address the config file.

**Comment by QilongTang** [comment]
@Racel Your PR is good to go, will add that info in my PR https://github.com/DynamoDS/DynamoRevit/pull/1742

**Comment by Racel** [comment]
Cool. Merging.

**Comment by QilongTang** [comment]
@Racel  Can you cherry-pick this into R2018 and R2016 branches as well? Let me know if you have any problems.

**Comment by Racel** [comment]
ok.

**Pull request merged**
