### PR TITLE
Update version to1 1

### PR DESCRIPTION
**Pull request by ZiyunShang**
### Purpose

Update version to 0.1.1 and create a new d4r package to Revit which fixed some bugs and improvements.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.

### Reviewers

@AndyDu1985 

### FYIs

@QilongTang @mjkkirschner

### CODE REVIEW

**Comment by ZiyunShang** [comment]
Hi @QilongTang @mjkkirschner , is the function **AddNodeDirectory** available here? I didn't find any similar use case in Dynamo Tests, what do I need to pay attention to when using it?

**Comment by Mikhinja** [comment]
Would this work with custom nodes, i.e. *.dyf files? Although we would categorize those as content for our package, it would still be nice to be able to test them.

**Comment by QilongTang** [comment]
@ZiyunShang In Dynamo tests, we use `GetLibrariesToPreload()` to preload dlls, for dyfs most of test case could simply open it to get them in library. Are you using it right now for preloading revit nodes developed by other Revit team? If this method works for you, then feel free to use it.

**Comment by ZiyunShang** [comment]
@QilongTang Thanks to your reply.
@Mikhinja I think this only work with dll files, but you can open dyf files in your test code to get them in library as Aaron said.

**Pull request merged**
