### PR TITLE
Update icon for Revit nodes

### PR DESCRIPTION
**Pull request by YanmengLi**
### Purpose

References: [MAGN-9872](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9872)
This PR is used to add 4 missing icons for Revit nodes:
Revit.Application.Document.FilePath
Revit.Elements.AdaptiveComponent.ByParametersOnCurveReference
Revit.Elements.AdaptiveComponent.ByParametersOnFace
Revit.Views.StructuralPlanView.ByLevel

Revit.Elements.AdaptiveComponent.ByParametersOnFace
byparametersonface

Revit.Elements.AdaptiveComponent.ByParametersOnCurveReference
byparametersoncurvereference

Revit.Application.Document.FilePath
filepath

Revit.Views.StructuralPlanView.ByLevel
structuralplan

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@Racel 

### FYIs

@riteshchandawar

### CODE REVIEW

**Comment by YanmengLi** [comment]
@Racel When I checked the ai files on google drive, I found some of the missing icons for Revit nodes have been created. It did not get correctly loaded because of wrong naming. After checking with @riteshchandawar, we found the old icons did not fully reflect the function of the nodes. I will create new ones for them. The large and small png files need to be saved in "...\Dynamo\src\Resources\RevitNodes". This is the folder that has been newly created. There is no folder to file the png files in DynamoRevit src code.

**Comment by Racel** [comment]
Thanks, @YanmengLi. The new icons looks great. 

We had made some recent changes regarding location of Revit icons for the Dynamo Dictionary project. Adding @ramramps to the discussion as he was part of the effort to move the Revit icons. @ramramps- any addition comments/insights?

**Comment by YanmengLi** [comment]
@Racel All the icons are done. I marked task MAGN-9872 as Under Review. Could you please review and let me know whether I need to make any changes? Thanks.

**Comment by Racel** [comment]
@YanmengLi - These look great! You can go ahead and merge when ready.

**Pull request merged**
