### PR TITLE
Changed CS.prop to support local folder in REVITAPI variable

### PR DESCRIPTION
**Pull request by tshcha**
### Purpose

For CICD we should take RevitAPI.dll and RevitAPIUI.dll from Artifactory and place them to Jenkins slave machine locally.
REVITAPI variable in CS.prop file should find that local folder.

The folder will be 

C:\Jenkins\workspace\DynamoRevit\lib\Revit 2019\net452

or

C:\Jenkins\workspace\amoRevit_DynamoRevit_master-G2TUPPOR2UKLZK2Z2BAQVNZG5F6X2PKEOD2IHSGYRLDKIJ5BHRAQ\DynamoRevit\lib\Revit 2019\net452

depending on folder where we'll decide to place Dynamo and DynamoRevit solution folders cloned from repo.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.

### Reviewers

Phil Xia
Aaron Tang
Siddhartha Mangarole

### CODE REVIEW

**Comment by QilongTang** [comment]
@tshcha @philxia1 Would you provide an example of the path to the PR description?

**Comment by tshcha** [comment]
@QilongTang Done.

**Comment by QilongTang** [comment]
@tshcha Sorry I saw that in the code but just want a real path to better understand what this change means

**Comment by tshcha** [comment]
@QilongTang @philxia1 
I've just updated CS.prop again. See changes ("File changed").

The folder will be 

C:\Jenkins\workspace\DynamoRevit\lib\Revit 2019\net452

or

C:\Jenkins\workspace\amoRevit_DynamoRevit_master-G2TUPPOR2UKLZK2Z2BAQVNZG5F6X2PKEOD2IHSGYRLDKIJ5BHRAQ\DynamoRevit\lib\Revit 2019\net452

depending on folder where we'll decide to place Dynamo and DynamoRevit solution folders cloned from repo.

**Comment by alfarok** [comment]
@philxia1 @QilongTang @ramramps @jnealb   Should these changes also be cherry-picked to the Revit 2019 branch?  When I try to build 2019 locally I noticed RevitAPI.dll and RevitAPIUI.dll references are missing?  I also noticed [this PR](https://github.com/DynamoDS/DynamoRevit/pull/1921/files) for the 1.3.3 2019 RC which also touches these dependencies.

**Comment by mjkkirschner** [comment]
@alfarok do you have revit 2019 installed on the machine you are trying to build on?

**Comment by alfarok** [comment]
@mjkkirschner no I didn't install Revit 2019.  @jnealb was seeing errors launching 2019 so I tried to build D4R 2019 locally to see if I ran into issues

**Comment by jnealb** [comment]
@mjkkirschner @alfarok Here is the version of 2019 I am testing against. Should I upgrade? 
image

**Comment by alfarok** [comment]
Please disregard, issue was unrelated.  We have asked the Revit team to roll-back the TSplines version used in Revit 2019.  Once that's done and only then can we test D4R 2019.

**Pull request merged**
