### PR TITLE
Cherry pick changes related to floor/roof, wallface, curtainsystem and familyinstance by geometry

### PR DESCRIPTION
**Pull request by fanwgwg**
### Purpose

Cherry pick changes from #1508, #1488, #1485, #1481, #1477 and #1473.

### Reviewers

@Randy-Ma

### CODE REVIEW

**Comment by Randy-Ma** [comment]
@fanwgwg 
Thanks again for the great effort! Apart from one inline comment, there seems to be one commit which is not cherry-picked - the one named as "FaceWall Tests added".

**Comment by fanwgwg** [comment]
Oops sorry for that, but thanks for pointing it out! Should I help fix that ?

**Comment by Randy-Ma** [comment]
Yes, that will be great!

**Comment by Randy-Ma** [comment]
@fanwgwg 
It seems there is one comment that you have not addressed.

**Comment by Randy-Ma** [comment]
@fanwgwg 
Great! Thanks again for the hard work!

**Comment by Randy-Ma** [comment]
@fanwgwg 
It will be great if you can apply a similar fix that is done in https://github.com/DynamoDS/DynamoRevit/pull/1528.

**Comment by fanwgwg** [comment]
@Randy-Ma just updated the version numbers!

**Pull request merged**
