### PR TITLE
Added Space.cs to allow for similar space creation methods.

### PR DESCRIPTION
**Pull request by sixtysecondrevit**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Room creation and parameter nodes were added a while back. There were none for space which use similar methods. so I went ahead and added a space class for all of the same methods.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by QilongTang** [comment]
@sixtysecondrevit Do you plan to add unit tests for the new class?

**Comment by sixtysecondrevit** [comment]
I'm still super new to this process. Let me read up on that some more. 😁 Apologies for that!

**Comment by QilongTang** [comment]
https://jira.autodesk.com/browse/QNTM-2824 Has been created to track this PR, FYI: @Racel @mjkkirschner  @sm6srw

**Comment by sixtysecondrevit** [comment]
Closing this as I plan on just rolling these nodes into a MEP-centric Dynamo package.

**Pull request closed without merging**
