### PR TITLE
add unit test cases for Revit2015

### PR DESCRIPTION
**Pull request by zora-wang**
### Purpose

Add unit test cases in branch Revit2015;
please notes the test cases added in revit2015 should only be run with  revit2015  & 2016,because .rvt has been updated, and cannot use to test in Revit2014 

### Reviewers

@monikaprabhu ,
@ke-yu

### CODE REVIEW

**Comment by ke-yu** [comment]
@zora-wang , please use PR template.

**Comment by monikaprabhu** [comment]
@zora-wang, 
1. Add verification for  Curves, Solid.ByUnion and Surface.Subtract methods in PerforationByImage.dyn
2. PanelWall.dyn - Add verification for Adaptive Components.

**Comment by zora-wang** [comment]
@monikaprabhu 
Tests have been updated

**Comment by zora-wang** [comment]
revit test files
@ke-yu @monikaprabhu   please help to review it thank you ~~ very much

**Comment by monikaprabhu** [comment]
LGTM

**Comment by zora-wang** [comment]
@monikaprabhu  it is in update panelwall and perforationsbyimage 88cf038

**Comment by ke-yu** [comment]
LGTM

**Comment by monikaprabhu** [comment]
ok.Thanks

**Pull request merged**
