### PR TITLE
Provides additional details for D4R tests referencing old YouTrack issues

### PR DESCRIPTION
**Pull request by alfarok**
### Purpose

[QNTM-3632](https://jira.autodesk.com/browse/QNTM-3632)

This PR provides additional details for D4R tests referencing old YouTrack issues.  In scenarios where a test simply referenced a YouTrack (MAGN-xxx) I attempted to provide a link to any GitHub commits or pull requests referencing the work while providing a short description regarding what is being tested.

I was unable to located details on:
`MAGN-3983`
`MAGN-438`
`MAGN-2589`
`MAGN-529`
`MAGN-7075`
`MAGN-8187`
`MAGN-66`

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [X] Snapshot of UI changes, if any.

### Reviewers

@QilongTang 

### FYI

@philxia1 @AndyDu1985 @ZiyunShang

### CODE REVIEW

**Comment by QilongTang** [comment]
@alfarok Great work! I remember that we may need to replace these test names to also use bug short description, I am sending an email inlcuding you to the Revit Team for confirmation. So hold on wrapping this up

**Comment by ZiyunShang** [comment]
I think this should be useful to make us clearly know what these tests did.

**Comment by QilongTang** [comment]
@ZiyunShang Can we merge this as it is? Do we need more changes in this PR?

**Comment by alfarok** [comment]
Merging on Master and Cherry-picking to 2017, 2018, 2018.  Please let us know if additional efforts are required.

**Comment by ZiyunShang** [comment]
@alfarok That's enough, thanks a lot for all your support.

**Pull request merged**
