### PR TITLE
Fix failing test cases

### PR DESCRIPTION
**Pull request by Randy-Ma**
This is to fix the failing test cases because of the changes related to the path manager. This also attributes one test case to the Failure category.

The following pull request need to be merged before this one.
https://github.com/DynamoDS/Dynamo/pull/3924

@ikeough 
PTAL

### CODE REVIEW

**Comment by RodRecker** [comment]
Thank you Randy and why is the one test being marked failure?

**Comment by Randy-Ma** [comment]
@RodRecker 
When an Revit element is modified, the node which creates it will be marked as dirty. This is causing an infinite loop for selection nodes. The old behavior(marking the node as dirty) is changed to fix this infinite loop. But this is breaking one existing test case.

To fix this test case, we either need to differentiate selection nodes and other nodes or come to a conclusion for new behavior and change the test case.

But either solution will need careful consideration and take a longer time. So I have temporarily marked the test case as failure.

**Comment by ikeough** [comment]
FYI. We started a story last week to include tasks around limiting number of executions. I put a line in there for this:
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6583

**Comment by ikeough** [comment]
I see that you're doing something here very similar to what we do in DynamoRevitApp. LGTM, as long as it doesn't run afoul of @Benglin's plans for the DynamoPathManager.

**Comment by Randy-Ma** [comment]
I am merging this to fix the failing test cases as the impact of the changes is limited to this test. But @Benglin, if whenever a DynamoPathManager singleton instance is created, it is usable, it will perfect for this case so that I do not need to set all the paths again.

**Comment by Benglin** [comment]
All is good, thanks for bringing this to my attention, @ikeough, @pboyer and @Randy-Ma. I got this under control.

**Pull request merged**
