### PR TITLE
fix to missing Material Wrapper

### PR DESCRIPTION
**Pull request by ksobon**
### Purpose

This PR addresses a missing Wrapper method for Material. Solves this issue: https://github.com/DynamoDS/DynamoRevit/issues/1581

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@mjkkirschner

### CODE REVIEW

**Comment by Racel** [comment]
Added to backlog. Will run tests and merge. We will let you know if we run into any issues.

**Comment by mjkkirschner** [comment]
This PR has a bunch of c# 6 features, and I think while we have installed newer version of visual studio on the build machines we have not made sure these features will build and made sure to target the correct versions of .net. I would prefer to just err on the side of caution for right now and simply revert these improvements while keeping the core functionality that @ksobon has added.

I also would like if statements to use braces unless the result is a return, and even then I prefer braces.

**Comment by Racel** [comment]
@mjkkirschner - So, are we asking @ksobon to do the following?:
- Revert the c#6 features
- update syntax to match coding standards
Can you please let us know if you will have time to fix these issues in the next couple of weeks? If not, please close and reopen at a later date.

**Comment by Racel** [comment]
@ksobon - As per our discussion, we are closing this task. Please feel free to reopen at a later date.

**Pull request closed without merging**
