### PR TITLE
area schedule support 2018

### PR DESCRIPTION
**Pull request by ksobon**
### Purpose

This PR addresses this issue: https://github.com/DynamoDS/DynamoRevit/issues/1704

image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@mjkkirschner @smangarole, @jnealb 

### FYIs

This was submitted before but was closed due to inactivity and lack of tests. Let's see if this works. It was tested: 

image

### CODE REVIEW

**Comment by QilongTang** [comment]
@ksobon Great work. But also be aware DynamoRevit work will be taken over by Revit team. I would @philxia1 @AndyDu1985 @ZiyunShang in the future for related work

**Comment by ksobon** [comment]
Really? @kronz @Racel @mjkkirschner I will miss you guys.

**Comment by QilongTang** [comment]
@ksobon Yes, DynamoRevit 2.0 should be the last release only handled by Dynamo team, in the future it will be joint effort.

**Comment by smangarole** [comment]
Thanks @ksobon. I am glad you were able to run the RTF tests.

**Comment by Racel** [comment]
@ksobon Don't worry. We will still be here, but focused on working on Dynamo Core only. The Revit team is just taking over the DynamoRevit repo :)

**Comment by mjkkirschner** [comment]
@ksobon this and the cherry picks look good to me - thanks for adding the new method, tests, and the general cleanup.
 - @philxia1 can we get this merged? I am not sure how you want to handle the new master branch though?

**Comment by AndyDu1985** [comment]
@ksobon, thank you for your contribution to Dynamo For Revit.

**Comment by AndyDu1985** [comment]
@ZiyunShang will cherry pick this PR to other branches.

**Comment by xpt5** [comment]
Is there any way of using the node in Dynamo 2.0.2 for Revit 2018.3? 
Thanks

**Pull request merged**
