### PR TITLE
Set Dynamo Core Selection Style

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose
Using the Dynamo Core Selection style in Dynamo Revit Controls

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@QilongTang 

### FYIs

@ZiyunShang 
@RobertGlobant20 
@filipeotero

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
@ZiyunShang Do we need to merge this?

**Comment by ZiyunShang** [comment]
@QilongTang I'm sorry for missing this PR, and I have a new PR about this, and I want to create a new d4r package for Revit there.

**Comment by QilongTang** [comment]
@ZiyunShang whatever the plan is, let us know, if you prefer to close this and merge the other one, I am also fine

**Comment by ZiyunShang** [comment]
> @ZiyunShang whatever the plan is, let us know, if you prefer to close this and merge the other one, I am also fine

I prefer to close this because only modifying the Selection Style will make the width of ComboBox and Button different, and also need to upgrade the version of DynamoCore lib to the latest.

**Pull request closed without merging**
