### PR TITLE
Update the master branch

### PR DESCRIPTION
**Pull request by ZiyunShang**
This PR would merge the branch RC1.3.3_Revit2019 to master branch.

### CODE REVIEW

**Comment by mjkkirschner** [comment]
This does not seem correct- what changes do you want to bing to master from -1.3?

**Comment by QilongTang** [comment]
@mjkkirschner The Revit team would like to use master branch in this repo to always align with Revit master branch, I feel like PR is too messy and does not mean too much. Should we simply delete master branch and create it based on RC1.3.3, and later for 2.0 we can do the same. This way it is easy and clean.

What do you think? @ZiyunShang @mjkkirschner

**Comment by ZiyunShang** [comment]
@QilongTang 
I think your method is very well, if there is no other problem.

**Comment by QilongTang** [comment]
@ZiyunShang Thanks, please close this PR and you can go ahead replace the master branch since you should have write access now

**Pull request closed without merging**
