### PR TITLE
Nugets NET 47 updates

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Follow up PR of https://github.com/DynamoDS/Dynamo/pull/9250. I will not merge until the new nugets are there on nuget.org

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.

### FYIs

@mjkkirschner @ZiyunShang @AndyDu1985

### CODE REVIEW

**Comment by QilongTang** [comment]
@ZiyunShang @AndyDu1985 @mjkkirschner I installed latest Revit Preview Release and sln built with this change. Merging. This should not impact the CI/CD but if it happens, let me know

**Comment by ZiyunShang** [comment]
Hi @QilongTang , is there a changelist in DynamoCore 2.1.0-beta6967? I found a new folder called IronPython.StdLib.2.7.8 was added. Is this a required component in Dynamo runtime?

**Comment by QilongTang** [comment]
@ZiyunShang That is a result of update to the newer version of IronPython. @alfarok This is expected new dlls added correct?

**Comment by ZiyunShang** [comment]
@QilongTang This folder contains a lot of Python files, I wonder if they all need to be added to the installation package? Or just components that are needed at compile time?

**Comment by mjkkirschner** [comment]
These are the core libraries of python - they need to be distributed with dynamo to support user code that relies on them. python nodes and packages containing python nodes.

**Comment by mjkkirschner** [comment]
see this PR for more info:
https://github.com/DynamoDS/Dynamo/pull/9180

**Comment by ZiyunShang** [comment]
@mjkkirschner OK, I get it. Thank you for your reply!

**Pull request merged**
