### PR TITLE
Change file open to be executed immediate.

### PR DESCRIPTION
**Pull request by QilongTang**
### Purpose

MAGN-9824 First File, Open fails silently with Dynamo4Revit
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9824

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.

### Reviewers
@sm6srw 

### FYIs

@mjkkirschner @ramramps 

Change file open to be executed immediate.
Instead of putting the file open action into the idleActionQueue, execute it immediately so that exception handling will be consistent with DynamoStudio. Since file open right now does not call Revit API, so execution should be fairly safe.

Making the change in R2017 branch first, if everything is good, submissions to other branches will follow.

### CODE REVIEW

**Comment by ramramps** [comment]
I am OK with this  change. But as Neal mentioned, can you please ensure the other task is good too? #
MAGN-5768

**Comment by ramramps** [comment]
Also, I am not sure whether there are test cases coupled with this behavior. 
@Randy-Ma - I would recommend you to take a look at this.

**Comment by sm6srw** [comment]
LGTM

**Comment by Randy-Ma** [comment]
As I can remember, this won't impact existing test cases. :)

**Comment by QilongTang** [comment]
Merging this one and testing same change in R2016, R2015.

**Pull request merged**
