### PR TITLE
fix to view export 2018

### PR DESCRIPTION
**Pull request by ksobon**
### Purpose

This addresses this issue: https://github.com/DynamoDS/Dynamo/issues/3262 (possibly but it's an old one) and this issue: https://github.com/DynamoDS/DynamoRevit/issues/1695

Basically the idea is that we use ImageExportOptions.GetFileName instead of manually constructing the predicted filename that Revit will assign to our export. It fails. 

image

Using their built in static method does not:

image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@mjkkirschner 

### FYIs

I am re-submitting this since last time it was closed without getting merged. My bad.

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@ksobon it's likely that some of our tests fail when run with these changes - did you ever get those running with RTF locally?

**Comment by mjkkirschner** [comment]
whoops sorry, didn't mean to close.

**Comment by ksobon** [comment]
@mjkkirschner never got the RTF running on my end. What are the issues? Why is it failing?

**Comment by ksobon** [comment]
@mjkkirschner poke

**Comment by ksobon** [comment]
@mjkkirschner I finally got the RTF setup so i am able to run the tests myself. You were right this one was failing due to some logic issues and variable conflation. Anyways, it's fixed now: 

image

I will cherry pick this to other branches as well. It looks like you guys are busy and cherry picks turn into turf wars. :-)

**Comment by mjkkirschner** [comment]
@ksobon nice! Glad you were able to get RTF setup.

**Comment by ksobon** [comment]
@mjkkirschner well to be honest it's still touchy as hell but it's working so i can't complain. 👍

**Comment by ksobon** [comment]
@mjkkirschner one more thing. 2019 branch wants me to install .NET 4.7 are you guys running that build from Visual Studio 2017? or should I just install the dev pack and continue working in VS15? I just want to make sure I have a similar setup to avoid issues.

**Comment by QilongTang** [comment]
@ksobon Most of our devs here are using VS15 with .Net4.7 dev pack, you can stick to this setup. If you are running VS17 that's also fine

**Comment by ZiyunShang** [comment]
I tried to run the RTF test, and it looks good.

**Pull request merged**
