### PR TITLE
Integrate DCore and D4R 2.1.0 to Revit 2020

### PR DESCRIPTION
**Pull request by ZiyunShang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

1.update D4R to 2.1.0 match the DCore version.
2.add DCore Samples and Gallery to D4R package in CICD.
3.update the version file to 23.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by mjkkirschner** [comment]
Hi @ZiyunShang 
https://github.com/DynamoDS/DynamoRevit/compare/Revit2019..master?expand=1

not sure if you want to also include missing cherry picks in this PR but there are some differences that are missing between 2020 branch and 2019 branch - for example - a bunch of overloads were removed from the 2019 branch to facilitate move to 2.0.

I just found out that doing `..` instead of `...` on GitHub diffs will check the heads of the branches instead of the commits which is very useful for this kind of comparison.

**Comment by mjkkirschner** [comment]
@AndyDu1985 @ZiyunShang  These changes look good, are you planning another PR to get the other changes in I see a few changes in 2019 that look worth while in the diff I linked above:
1. updated text transform using visual studio 2017 text transform utils
2. updated adaptive component test
3. overloads removed to cleanup DyanmoRevit library (@sm6srw  can say more about that)

diff also shows one odd thing:

4. revit icons have had versions added but they say 2019 on them

**Comment by ZiyunShang** [comment]
Hi @mjkkirschner , the revit icons' version was added because there should not be non-versioned file in Revit addin.

**Comment by mjkkirschner** [comment]
@ZiyunShang yep got that, but shouldn't it be updated to 2020?

**Comment by ZiyunShang** [comment]
@mjkkirschner It will be updated to 2020 when Revit 2020 released.

**Comment by sm6srw** [comment]
The overloads commit should definitely be cherry-picked over to the 2020 branch. One of the changes in 2.0 is to not allow function overloads which only diff in parameters' rank (more information here: https://github.com/DynamoDS/Dynamo/pull/8140). This was mainly a concern for Dynamo and LibG. My commit takes care of the few overloads that existed in D4R.

**Comment by ZiyunShang** [comment]
Hi @mjkkirschner , What do you mean by the updated text transform using visual studio 2017 text transform utils? Do I need to use the TextTransform tool to do something?
And with the commits for DynamoCore, what do I need to do in D4R, @sm6srw ?

**Comment by mjkkirschner** [comment]
Hi @ZiyunShang 

1. if you look at the diff I posted above - this code is missing from master branch:
 in the file `src/transform_all.bat` I just don't want to lose this improvement.
```
)
IF EXIST "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Professional\Common7\IDE\TextTransform.exe" (
    set TEXTTRANSFORMPATH="%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Professional\Common7\IDE\TextTransform.exe"
)
IF EXIST "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\TextTransform.exe" (
    set TEXTTRANSFORMPATH="%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\TextTransform.exe"
)
IF EXIST "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\IDE\TextTransform.exe" (
    set TEXTTRANSFORMPATH="%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\IDE\TextTransform.exe"
)
```

2. I think the overloads were removed from master at some point - or at least I don't see them in the diff any longer, lets forget about that for now. I'll dig a bit more.

I think this looks good to go @ZiyunShang.

**Comment by ZiyunShang** [comment]
@mjkkirschner I think this looks good to D4R. Revit dev environment was migrated to VS2017 recently,  this change is necessary cherry-pick to master branch! Thanks a lot for your review!

**Pull request merged**
