### PR TITLE
fix to element.movebyvector that throws transaction errors

### PR DESCRIPTION
**Pull request by ksobon**
### Purpose

This addresses this issue: https://github.com/DynamoDS/DynamoRevit/issues/1691

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@mjkkirschner

### CODE REVIEW

**Comment by ksobon** [comment]
While I was at it, I made that method return the element that it was supposed to move. That's to prevent these nodes from becoming dead ends. I don't see why it should return `void`.

**Comment by smangarole** [comment]
@sm6srw Can you please take a look at this commit when you get a chance? 
@QilongTang FYI.

**Comment by Racel** [comment]
We are concerned that returning Element might cause an infinite loop. We ran into something similar when we were implementing Rotate. We will test on our machines before merging.

Or, if you have time, please let us know if you noticed any strange behavior.

**Comment by Racel** [comment]
@ksobon - As per our discussion, we are closing this task. Please feel free to reopen at a later date.

**Pull request closed without merging**
