### PR TITLE
Cross merge in Revit2016

### PR DESCRIPTION
**Pull request by zora-wang**
### Purpose

* cross-merge https://github.com/DynamoDS/DynamoRevit/pull/538

### Reviewer
@monikaprabhu 
cc: @riteshchandawar 

Thanks

### CODE REVIEW

**Comment by riteshchandawar** [comment]
Hello Zora,

Once you do the cross merge, you should do the save as on Revit files, so that Revit 2016 project should have Revit files which are saved in Revit 2016.

And as peter mentioned, please make the summary descriptive. :)

**Comment by zora-wang** [comment]
@riteshchandawar ,  yes I have updated the rvt file to higher version already. please see the second commits.~~:*)

**Comment by monikaprabhu** [comment]
@zora-wang - please fix the file path used in the .dyn file

**Comment by riteshchandawar** [comment]
LGTM!

**Comment by monikaprabhu** [comment]
thanks Zora for resolving issues in comments.

**Pull request merged**
