### PR TITLE
Update app to use the new RenderPackageCache API changes

### PR DESCRIPTION
**Pull request by ColinDayOrg**
### Purpose

This PR updates D4R (2017) to incorporate the RenderPackageCache changes.

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [X] Snapshot of UI changes, if any.

### Reviewers

@mjkkirschner 

### FYIs

@QilongTang

### CODE REVIEW

**Comment by QilongTang** [comment]
Do you plan to cherry-pick this into other Revit Version Branches as well after this is merged?

**Comment by ColinDayOrg** [comment]
Yes. On the assumption that this PR was ok I actually have branches QNTM-2631_2018 and QNTM-2631_2019 cherry-picked and waiting. 

Do we do PR's for cherry picked changes? I'm guessing no, but I don't know what the team policy is.

Also, does merging into Revit2017, Revit2018 and Revit2019 branches cover all the branches that would need updating?

**Comment by QilongTang** [comment]
Yes, we do PRs. There is no policy around it, sometimes we skip that if it's one line change. But for cherry-pick PRs, you can just make PR and merge them.

Since your Dynamo change is only in `master` branch, I think R2017 - R2019 branches are enough

**Comment by ColinDayOrg** [comment]
Sorry, I meant code reviews, not PRs.

**Comment by QilongTang** [comment]
@ColinDayOrg Code review is good anyway. Changes looks good to me 👍

**Comment by mjkkirschner** [comment]
LGTM

**Pull request merged**
