### PR TITLE
Fix list duplication in node Revit>Selection>Views

### PR DESCRIPTION
**Pull request by dimven**
### Purpose

Currently, every time you select the drop-down list the views are added over and over to it. So after a few times of that, you end up with an incredibly long list of duplicate values and can't easily find the view you're looking for.

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files

### FYIs

I don't believe we should add any new tests because no new functionality was exposed.

### CODE REVIEW

**Comment by RodRecker** [comment]
@dimven Thank you!
@mjkkirschner Can you take a look or reassign to someone more appropriate?

**Comment by mjkkirschner** [comment]
@dimven thanks for this PR, can you also create PRs for 2016 and 2017? Then I will merge them all at once.

**Comment by dimven** [comment]
@mjkkirschner Sorry about the long delay. This completely slipped my mind after my holiday.

I was not able to add all three branch changes under a single PR and had to create two separate PRs. Is that the general practice, or have I fumbled something?

**Comment by mjkkirschner** [comment]
3 PRs is the way, I'll take a look asap.

**Pull request merged**
