### PR TITLE
fix to inconsistent element.getCategory naming

### PR DESCRIPTION
**Pull request by ksobon**
### Purpose

This is super small, but addresses consistency in naming conventions pointed out here: 

https://github.com/DynamoDS/DynamoRevit/issues/1663

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@Racel @kronz @mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
this and I think getLocation - requires a migration as it will break old graphs.

**Comment by ksobon** [comment]
do we have an example?

**Comment by Racel** [comment]
@mjkkirschner - Can you provide some feedback on this?

**Comment by mjkkirschner** [comment]
@ksobon look at the migration xml files or the `[AlsoKnownAs]` attribute, these both allow renaming of zero touch nodes. The migration xml allows moving to other categories as well.

**Comment by Racel** [comment]
@ksobon - We are trying to go through several of your PRs. Can you please let us know if you will have time to look into the migration issues above outlined by @mjkkirschner  in the next couple of weeks? If not, please close and reopen at a later date.

**Pull request closed without merging**
