### PR TITLE
Fix compatibility with Revit2019-1

### PR DESCRIPTION
**Pull request by BogdanZavu**
### Purpose
Fix compatibility with Revit2019-1

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers
@QilongTang

### CODE REVIEW

**Comment by BogdanZavu** [comment]
FYI : @dobriai

**Comment by QilongTang** [comment]
@BogdanZavu @smangarole We are seeing some Revit version mismatch here. The branch is building fine on our build machine, can you guys all report here the Revit version number?

**Comment by BogdanZavu** [comment]
@QilongTang does the build machine have latest version of 2019.1 ? for which the current branch is in fact release/2019

**Comment by QilongTang** [comment]
@smangarole is on the way of updating Revit to latest on build machine. Will defer to him

**Comment by QilongTang** [comment]
LGTM @smangarole As @BogdanZavu Indicated, the old APIs have been deprecated correctly now and it is still better that we use the new APIs

**Comment by QilongTang** [comment]
@BogdanZavu  Mind cherry pick this to R2019 branch as well?

**Pull request merged**
