### PR TITLE
fix SunSettings crash in Revit 2016  - MAGN-7298

### PR DESCRIPTION
**Pull request by tatlin**
## Purpose

fix for SunSettings Dynamo crash and Revit 2016 API context issue
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7298

### Declarations

Check these iff you believe they are true

- [X] The code base is in a better state after this PR
- [ ] The level of testing this PR includes is appropriate - NOTE I did not add any new tests to ensure this is covered. I also did not test this change in Revit 2014 or 2015 but the change I made (adding a DynamoRevit.AddIdleAction wrapper) follows the same pattern that exists in other locations like SiteLocation.cs

### Reviewers

@ikeough 

### FYIs

@monikaprabhu @riteshchandawar @jnealb 

#### Merges:
- [ ] Revit2014
- [ ] Revit2015
- [ ] Revit2016

### CODE REVIEW

**Comment by RodRecker** [comment]
Who is reviewing this?


Rod




On Wed, May 6, 2015 at 5:36 PM -0700, "Matt Jezyk" <notifications@github.com<mailto:notifications@github.com>> wrote:


fix for SunSettings Dynamo crash and Revit 2016 API context issue

http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7298

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/DynamoDS/DynamoRevit/pull/359

Commit Summary

  *   fix SunSettings crash in Revit 2016 - MAGN-7298

File Changes

  *   M src/Libraries/RevitNodesUI/SunPath.cs<https://github.com/DynamoDS/DynamoRevit/pull/359/files#diff-0> (20)

Patch Links:

  *   https://github.com/DynamoDS/DynamoRevit/pull/359.patch
  *   https://github.com/DynamoDS/DynamoRevit/pull/359.diff

-

**Comment by tatlin** [comment]
Ian was set in the PR but feel free to reassign 

-matt

**Comment by tatlin** [comment]
@ikeough can you look at this today? I'd like to get something back to David.

**Comment by ikeough** [comment]
@tatlin Please add one test to `RevitSystemTests` to ensure that SunSettings update is covered. 

I've also added a "Merges" section to the PR description.

**Comment by tatlin** [comment]
There are 7 tests already here RevitNodesTests\Elements\SunSettingsTests.cs, should i move one over to RevitSystemTests?

**Comment by riteshchandawar** [comment]
@tatlin I can help adding RevitSystemTests for this functionality. Do I need to pull Matt's brnach or can we merge this PR and then I will add System Tests and send PR from my branch. I can create Task to create System Tests.

Thanks,
Ritesh

**Comment by tatlin** [comment]
Thanks @riteshchandawar. Also how is merging into 2015/2014 typically handled?

**Comment by riteshchandawar** [comment]
@tatlin For Revit 2015 and 2016 you need to cherry pick commits from this PR and send separate PR's from those two branches.

**Comment by tatlin** [comment]
I have created I made a new SunSettings RevitSystemTest today while at a conference, It runs cleanly without the Assert.AreEqual test., I am clearly not using Assert.AreEqual right if a double is failing because the 15th significant digit is different, but the delta is set to .001

**Comment by riteshchandawar** [comment]
@tatlin I showed this to @Randy-Ma and he said it shouldn't fail when there is a tolerance value 0.001, we should log a defect for this.

For now I think we should just check the value should not be Null.

**Comment by jnealb** [comment]
@tatlin @Randy-Ma @riteshchandawar @RodRecker @mccrone Candidate for the "do the math" epic/task?

**Comment by tatlin** [comment]
system test updated to just be a null check.  We are ready to merge this in my opinion.

**Comment by riteshchandawar** [comment]
On latest build I am still seeing a Crash on top of Revit 2016.

Does this will also fix "Solar Analysis for Dynamo" package as well?

Thanks,
Ritesh

**Comment by tatlin** [comment]
Crash where? This fix does not depend on solar analysis, but solar analysis does depend on sun settings 

-matt

**Comment by riteshchandawar** [comment]
Crash while placing SunSettings.Current Node when Dynamo running on top of Revit 2016.
image

**Comment by tatlin** [comment]
Using rc8.0_revit2016 branch?

**Comment by riteshchandawar** [comment]
oooh I didn't notice you submitted to RC0.8.0 branch, I was testing it on Master.
There is no Build from that branch as it is release I think we stopped making build from RC branch.
Let me ask EC folks to trigger build based on your changes.

But we need to submit this to master branch as well right?

**Comment by tatlin** [comment]
I submitted to RC0.8.0_Revit2016 but will open a new PR now to submit to Revit2016, which I believe is what the daily builds from master pick up

**Comment by tatlin** [comment]
opened separate PR for that branch https://github.com/DynamoDS/DynamoRevit/pull/365

**Pull request merged**
