### PR TITLE
Remove and Sort usings in D4R

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Remove and Sort Usings to reduce compile time and maintain code cleanness

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.

### FYIs

@AndyDu1985 @ZiyunShang

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@QilongTang this order of usings is not standard with the organize usings command in visual studio code - to match this order I think you need to install whatever extension you used... not sure this is a great idea.

**Comment by QilongTang** [comment]
@mjkkirschner The default setting is ordering system usings after customized ones and there is a setting in VS studio for you to flip it. This is based on Dynamo's code base, most of the files have system usings before customized one so I have made it part of our coding standard.

**Comment by QilongTang** [comment]
@mjkkirschner If you want to make the default behavior same with coding standard, I can point the Visual Studio setting in coding standard. Unless you prefer we go through the whole code base to revert all the orders, I am fine with that approach as well.

image

**Comment by QilongTang** [comment]
@mjkkirschner I will add it to the coding standard, any other place you think we should also add?

**Comment by erfajo** [comment]
good job @QilongTang, thanks a lot for the hint :-)

**Pull request merged**
