### PR TITLE
Add regression tests for samples

### PR DESCRIPTION
**Pull request by ZiyunShang**
### Purpose

 Add Dynamo Samples to RevitSystemTests.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.

### Reviewers

@AndyDu1985 

### FYIs

@QilongTang @mjkkirschner

### CODE REVIEW

**Comment by QilongTang** [comment]
Other than maintaining a copy of all those samples in this repo, maybe making the project depending on the nuget so samples will always be pulled before running the test?

**Comment by ZiyunShang** [comment]
Hi @QilongTang , these tests would be added to Revit Regression tests later. I think it would be better to put them in the same working directory as other SampleTests.

**Comment by QilongTang** [comment]
hmmm @ZiyunShang do you mean in the future when we add samples, they all need to be migrated manually?

**Comment by ZiyunShang** [comment]
Hi @QilongTang , I misunderstood your opinion. I have removed Sample files from Test folder and get them from nuget when build DynamoRevit.
I also updated the rvt file version of DynamoSample - from 2015 to 2020 now.

**Comment by ZiyunShang** [comment]
@AndyDu1985 could you help merge this, please?

**Pull request merged**
