### PR TITLE
allow a graph to be opened and executed using journal directives

### PR DESCRIPTION
**Pull request by BogdanZavu**
### Purpose
We want to be able to open a *.dyn file in Dynamo using journal directives when this action is requested from an external application.

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [X] Snapshot of UI changes, if any.

### Reviewers
@mjkkirschner 

### FYIs
@dobriai

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@BogdanZavu I think this is good to merge, just curious, are you using journal files to execute graphs primarily for testing or something else?

**Comment by BogdanZavu** [comment]
Hi Mike,
It's not just for testing. We are using DynamoRevit.ExecuteCommand(DynamoRevitCommandData commandData) to perform all our operations on the inner DynamoModel/DynamoViewModel in order to preserve the same Revit start-up/execution context and not worry about future changes.
We don't have many operations , basically we just want to open and/or execute a *.dyn file and there are already journal directives for these actions.

**Comment by mjkkirschner** [comment]
@BogdanZavu there is now a 2018 branch which @sm6srw will be updating soon.
Can you also create a PR for this change on the 2018 branch which cherry picks this change there.

**Comment by BogdanZavu** [comment]
Thank you @mjkkirschner 
I created a PR for Revit2018 branch also.

**Pull request merged**
