### PR TITLE
fix to failing familyInstance.getType node

### PR DESCRIPTION
**Pull request by ksobon**
### Purpose

This addresses this issue: https://github.com/DynamoDS/DynamoRevit/issues/1652

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.

### Reviewers

@mjkkirschner 

### FYIs

I had to add an extra obsolete class to fix something else, but it's just temporary before next release when we can just delete them all. Right?

### CODE REVIEW

**Comment by kronz** [comment]
@ksobon this one is going to need some more extensive review. @sm6srw can you say a little about why this one is a little more complicated?

**Comment by ksobon** [comment]
@kronz why? All I did was clean up and make consistent the type retrieval methods. For some reason they weren't working consistently.

**Comment by mjkkirschner** [comment]
I know one issue is that there are c# 6.0 features in this PR which might cause problems with older versions of revit - we need to check with addin team.

**Comment by sm6srw** [comment]
New PR is #1780.

**Pull request closed without merging**
